# Generated by Django 4.2.7 on 2023-11-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('padres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones_Padres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificaciones.notificaciones')),
                ('id_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padres.padres')),
            ],
        ),
    ]
