# Generated by Django 4.2.7 on 2023-11-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaciones',
            name='fecha_creacion',
        ),
    ]
