# Generated by Django 4.2.7 on 2023-11-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='fecha_realizacion',
        ),
    ]
