# Generated by Django 4.2.7 on 2023-11-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padres', '0001_initial'),
        ('jardines_infantiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('id_jardin_infantil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardines_infantiles.jardinesinfantiles')),
                ('id_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padres.padres')),
            ],
        ),
    ]
