# Generated by Django 4.2.7 on 2023-11-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='fecha_vencimiento',
        ),
    ]
