# Generated by Django 4.2.7 on 2023-11-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jardines_infantiles', '__first__'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=255)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupos')),
                ('id_jardin_infantil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardines_infantiles.jardinesinfantiles')),
            ],
        ),
    ]
